# DB
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  #gmail SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: UTF-8
    protocol: smtp
    username: ENC(9NlYFfJbK5Epx/lOVqJGRvbtU5BWSytOZx8qNOgf1tE=)
    password: ENC(QM4Aq26vJvLXQcvIBRlP5UUOkE33ZB0P)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

jwt:
  header: Authorization
  secret: secret

social:
  github:
    url: https://api.github.com/user
  google:
    url: https://www.googleapis.com/oauth2/v2/userinfo
  facebook:
    url: https://graph.facebook.com/v6.0/me

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

api:
  cors:
    allow-origins: ENC(MUx6CLsdon60zBEAbQ+k0aHjrEkt5/6olFrgs11l7Wjo1VwjzoumVltRKR133vMsTPAp6vQlrCLHZOqniOrBUg==)

kafka:
  bootstrap-server: localhost:9092
