# DB
spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  #gmail SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: UTF-8
    protocol: smtp
    username: ${MAIL_EMAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    smtp:
      ssl:
        enable: true

token:
  key: Authorization

social:
  github:
    url: https://api.github.com/user
    token: ${GIT_TOKEN}
  google:
    url: https://www.googleapis.com/oauth2/v2/userinfo
  facebook:
    url: https://graph.facebook.com/v6.0/me
