# DB
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  #gmail SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: UTF-8
    protocol: smtp
    username: ENC(9NlYFfJbK5Epx/lOVqJGRvbtU5BWSytOZx8qNOgf1tE=)
    password: ENC(QM4Aq26vJvLXQcvIBRlP5UUOkE33ZB0P)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ENC(IWFzVDnmYftUSyaOA8mwXEciX/DRpdDAFQv4M7PR460=)
            clientSecret: ENC(Ql1c8B1ZI5AynPFr1yyrQ528PmblCLAmzqVSjzD4Y3cIaQ+l9ULmQqX11Hfg/bRBqT73K8UD0MU=)

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

jwt:
  header: Authorization
  secret: secret

oauth2:
  authorizedRedirectUrl: https://eussya-eussya.com/oauth/github


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

api:
  cors:
    allow-origins: ENC(MUx6CLsdon60zBEAbQ+k0aHjrEkt5/6olFrgs11l7Wjo1VwjzoumVltRKR133vMsTPAp6vQlrCLHZOqniOrBUg==)
