# DB
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  #gmail SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: UTF-8
    protocol: smtp
    username: ENC(9NlYFfJbK5Epx/lOVqJGRvbtU5BWSytOZx8qNOgf1tE=)
    password: ENC(QM4Aq26vJvLXQcvIBRlP5UUOkE33ZB0P)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ENC(xN+dbkNMVVF++uSOT4m+stmqK8dY/QSmJOWGr7lWLMo=)
            clientSecret: ENC(jU9A80TddJ9UFjQJb07tugRycItMuallO+OSyqz4efkvA1W4HTgwoEErZsRvilGKEZB+6cR/9dY=)

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

jwt:
  header: Authorization
  secret: secret


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

api:
  cors:
    allow-origins: ENC(MUx6CLsdon60zBEAbQ+k0aHjrEkt5/6olFrgs11l7Wjo1VwjzoumVltRKR133vMsTPAp6vQlrCLHZOqniOrBUg==)
